### ISSUE TITLE
Bonding Issue- Application unbond devices when multiple devices are connected with batch autoconnect

### ISSUE THREAD

**Issue by droideveloper1996** [weliem/blessed-android#115]
I am currently doing an automation project  with ble mesh and I was using batch auto-connect to connect to multiple devices for backup connection and then I realizes that when I was connecting to more than some x no of devices. The device was unbonding some of the previously connected devices and was showing a pairing popup. 

I tried auto-connect with NRF connect but I didn't face that issue. I am sure that I didn't reach BLE max connection I guess with the Samsung s7 edge it is supposed to be 15.

**Comment by weliem** [comment]
Please provide a log that shows the problem

**Comment by weliem** [comment]
Closing due to lack of information...
