### ISSUE TITLE
Remove Checkbox - Allow access to contacts.

### ISSUE THREAD

**Issue by kartic-techindustan** [weliem/blessed-android#128]
Hi,
We are having complaint as to why is app asking for contact permission.
I know this is default android popup. 
Is there a way to remove this - "Allow access to your contacts and call history." ?

![pairing](https://user-images.githubusercontent.com/80379493/144214335-6191033e-5774-4839-a8e0-49d0067a509b.jpeg)

**Comment by martijnvanwelie** [comment]
Unfortunately there is nothing you can do about this. It is a system dialog.

I suggest you file a 'bug' at Google.
