### ISSUE TITLE
Feature Request/Bug -- Force Indications over Notifications when a peripheral supports both

### ISSUE THREAD

**Issue by noellemorris** [weliem/blessed-android#131]
In [BluetoothPeripheral#setNotify](https://github.com/weliem/blessed-android/blob/a12ef0dd45ce823618181d4578ebafb5a89beaeb/blessed/src/main/java/com/welie/blessed/BluetoothPeripheral.java#L1420-L1423), there is an issue where notifications are favored over indications when both are supported. However, some BLE devices support both, and there should be a way to force indications if requested.

**Comment by weliem** [comment]
Indeed, this is what setNotify() does... intentionally! And so does setNotify on iOS and similarly on Linux Bluez. So it fairly common to do so.

On the other hand, you could argue that you should be able to choose indications or notifications if both are supported. Technically this is easy to fix. However, notifications are faster than indications and I don't know of any real-life situation where you would want to prefer indications over notifications for a characteristic that supports both.....do you have a good example?
