### ISSUE TITLE
AAPT: error: attribute android:usesPermissionFlags not found

### ISSUE THREAD

**Issue by WanManito** [weliem/blessed-android#138]
Version 2.1.6
-----------
 minSdk 21
 targetSdk 30
 compileSdk 30
 ------------------------
 An error was reported importing the library to compile

**Comment by WanManito** [comment]
Version 2.0.6  normal use

**Comment by weliem** [comment]
Set targetSDK and compileSdk to 31

**Comment by WanManito** [comment]
Hello, when I upgrade to a higher version, I found that I can't scan my device, but the surrounding watch devices can scan it. I don't know why?
