### ISSUE TITLE
Retrieving Battery information

### ISSUE THREAD

**Issue by Varsha-Kulkarni** [weliem/blessed-android#152]
Hi, I have tried the sample with Nonin Pulse Ox and A&D BP Monitor which read 2a19 and gives battery info. But the same when tried on different Glucose meters (Contour, AccuCheck Guide and GuideMe) don't return the service at all. Is there any way or it is the peripheral limitation that we cannot get the battery service discovered.

**Comment by weliem** [comment]
Not every device has the battery service, so that is why you sometimes see it and sometimes not
