### ISSUE TITLE
Omron BLE device - Bonding failed

### ISSUE THREAD

**Issue by ameenamuneer** [weliem/blessed-android#160]
Hi Weliem
First of all thank you for sharing this code. I faced the issue of failed bonding while connecting to OMRON BP device via android tab(Android 10 - Samsung SM-T290). Its working perfectly fine with Mobile phones(Android 11 - LG Wing) with version.

D/BluetoothPeripheral: starting bonding with 'BLESmart_0000045828FFB2BF00D9' (28:FF:B2:BF:00:D9)
D/BluetoothPeripheral: pairing request received: PAIRING_VARIANT_CONSENT (3)
D/ViewRootImpl@74238d3[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@4c16acc[MainActivity]
D/InputMethodManager: getNavigationBarColor() -855310
D/ViewRootImpl@74238d3[MainActivity]: Relayout returned: old=(0,0,1280,800) new=(0,0,1280,800) req=(1280,800)0 dur=15 res=0x1 s={true 481569972224} ch=false
D/ViewRootImpl@74238d3[MainActivity]: MSG_RESIZED: frame=(0,0,1280,800) ci=(0,36,0,72) vi=(0,36,0,72) or=2
D/ViewRootImpl@74238d3[MainActivity]: stopped(false) old=false
E/BluetoothPeripheral: bonding failed for 'BLESmart_0000045828FFB2BF00D9', disconnecting device

**Comment by weliem** [comment]
This looks like an issue with your tablet....
