### ISSUE TITLE
[feature] make public stopAutoconnectScan

### ISSUE THREAD

**Issue by paymicro** [weliem/blessed-android#161]
I would like to stop auto connect in my code.
When a user has several devices and needs to connect to one of them. When switching between them, auto-connection to the previous one must be disabled.
Now I have to use reflection for this.
Thanks.

**Comment by weliem** [comment]
In order to stop an autoconnect, just call cancelConnection()

**Comment by paymicro** [comment]
Thanks for the clarification, I didn't notice this possibility myself =)
