### ISSUE TITLE
Possibility of exposing BluetoothDevice

### ISSUE THREAD

**Issue by sylwia-golonko** [weliem/blessed-android#162]
`BluetoothCentral` currently exposed only mac addres, name and mtu. Can the library also expose the whole `BluetoothDevice`? It contains a lot of useful methods (e.g. for bonding) that can't be accessed via `BluetoothCentral` .

**Comment by weliem** [comment]
I added a method getBondState() to BluetoothCentral and released version 2.3.3.

I don't think there is much more interesting stuff you can ask BluetoothDevice. What else do you need?

**Comment by sylwia-golonko** [comment]
Things related to bonding, like:
- force bonding (`createBond`), at least there is another way to force it on server side 
- accept pairing popup `setPairingConfirmation` (system app)

Thanks in advance.

**Comment by weliem** [comment]
just released a new version that also offers createBond() and setPairingConfirmation()....2.3.5

**Comment by weliem** [comment]
closing this issue since requested functions are now available...
