### ISSUE TITLE
getCentralsWantingNotifications/getCentralsWantingIndications return disconnected central

### ISSUE THREAD

**Issue by syahvian** [weliem/blessed-android#166]
Hello, thanks for amazing library. I am having a issue. I am using the Android phone as a peripheral, when a central disconnected without unsubscribe characteristic first, the registered central data still remain in `centralsWantingNotifications`/`centralsWantingIndications`

**Comment by weliem** [comment]
Yes, I am aware and already working on a fix

**Comment by weliem** [comment]
Just released 2.4.0 that contains fix.

Note that for bonded devices the central is NOT unregistered, because that is how it should work according to the Bluetooth specification

**Comment by syahvian** [comment]
OK, thank you
