### ISSUE TITLE
If you use CentralManager and PeripheralManager together, BluetoothCentralManager.cancelConnection() does not work.

### ISSUE THREAD

**Issue by bagmin33** [weliem/blessed-android#173]
I am not good at English. Sorry

If you use BluetoothCentralManager and BluetoothPeripheralManager together, 
The BluetoothCentralManager.cancelConnection() function does not work.

    public void initBluetooth(Context context) {
        bluetoothManager = (BluetoothManager) context.getSystemService(Context.BLUETOOTH_SERVICE);
        bluetoothAdapter = bluetoothManager.getAdapter();
        bluetoothCentralManager = new BluetoothCentralManager(context, bluetoothCentralManagerCallback, new Handler(Looper.getMainLooper()));
        bluetoothPeripheralManager = new BluetoothPeripheralManager(context, bluetoothManager, bluetoothPeripheralManagerCallback);
    }

1. call bluetoothCentralManager.cancelConnection() 
2. response BluetoothCentralManagerCallback.onDisconnectedPeripheral() status is SUCCESS 
3. but It was not actually disconnected. (T^T)

Please help me.

**Comment by weliem** [comment]
Can you provide a log so that I can see what is going on?

**Comment by weliem** [comment]
Closing due to lack of information
