### ISSUE TITLE
In Samsung S22 series smartphones not working.

### ISSUE THREAD

**Issue by karthick1611** [weliem/blessed-android#175]
Hi,

I tried implement your library, everything working fine but In Samsung S22 series smartphones (Android 13), after sometime it's disconnected.

For example, I writing some commands to my charger and I'm able to read the response as well. That's not a issue but after some seconds, writing getting failed and bluetooth getting disconnected.

But In other Android 13 devices and Samsung devices, it's working fine.

Is that any issue in Samsung S22 series?.

**Comment by karthick1611** [comment]
Same commands what I'm sending working perfectly in Other devices. And it's good to know, u r developing for S22. May be, u'll get to know about this issue. While sending the data to my charger, while writing the data Bluetooth disconnected and writing failed.

**Comment by weliem** [comment]
well, there is one problem with the S22 and that is changing the MTU. It will say that it works, but it doesnt. You can check by removing the requestMtu() call so that it stays on the default 23.

**Comment by karthick1611** [comment]
Well.. Well.. Well.. It's working now but there's a issue as well. 

value byte array is longer than allowed by MTU, write will fail if peripheral does not support long writes

Getting this and not getting response fully.

**Comment by karthick1611** [comment]
Any Updates?.

**Comment by karthick1611** [comment]
I didn't mention there is issue with this library. 

And Thanks for the replies bro.

**Comment by karthick1611** [comment]
I didn't mention there is issue with this library. 

And Thanks for the replies bro.

**Comment by karthick1611** [comment]
As far as I tested, I believe Request MTU not working in Bluetooth Version 5.2. Is anyone faced the same issue?.

**Comment by weliem** [comment]
Closing this issue since it relates to S22 bug and is not a library issue
