### ISSUE TITLE
Foracare & i-sens devices support?

### ISSUE THREAD

**Issue by Sami32** [weliem/blessed-android#176]
I'm wondering if these FDA approved devices are supported or if they are planned?

- CareSens N Premier (Continua certified)
https://i-sens.com/blood-glucose-monitoring-system/

- Nonin 9591
https://www.nonin.com/support/9591/

- Fora Diamond Mini
https://www.foracare.ch/blood-glucose-monitors/

- MIR Spirobank Smart
https://spirometry.com/en/products/spirobank-smart/

- Vitalograph ASMA-1 BT
https://vitalograph.com/product/asma-1-bt/

**Comment by weliem** [comment]
Well, this is a BLE library and the demo application happens to work with some health devices. But I am not 'supporting' any devices in general...

Nonetheless, the Glucose meters might work, but the others won't I think....
