### ISSUE TITLE
Bluetooth Connection Issues

### ISSUE THREAD

**Issue by thy-hoang-nn** [weliem/blessed-android#179]
Hello, I am interested in your library and have used it to create my application.

Is there anything to check when Bluetooth is turned off, though? I'm referring to when your Bluetooth LE device is moved far from your phone and there is a connectivity problem. If you maintain your devices within Bluetooth range, they will be linked and their data, including any previously unsent data, will be sent to your phone.

I hope you will reply as soon as possible and thanks for other supports.

**Comment by weliem** [comment]
You can use central.isBluetoothEnabled()

**Comment by weliem** [comment]
When a device gets out of range, the connection is automatically broken. Similarly when BLE is turned off, the connection will be lost...
