### ISSUE TITLE
Expose requestConnectionPriority()

### ISSUE THREAD

**Issue by moffa90** [weliem/blessed-android#18]
Could you expose requestConnectionPriority(), to change connection interval please?

**Comment by weliem** [comment]
Sure, I just release a new version (0.14) that exposes the requestConnectionPriority method

**Comment by weliem** [comment]
Can you test it?

**Comment by moffa90** [comment]
Seems to be working properly, thank you

**Comment by weliem** [comment]
Ok thanks for testing. Will close this issue
