### ISSUE TITLE
Messages without a timestamp (flag = 0) result in a null pointer exception

### ISSUE THREAD

**Issue by crane-soft** [weliem/blessed-android#191]
I did make some tests with the sample app. My server application runs on a small arduino which sends all flags = 0 and then only the temperature value. Therefore the TemperatureMeasurement  class donot set the timestamp and the type, so the timestamp is null. Unfortunately the temperatureDataReceiver does not take care about a missing timstamp.
My solution so far is setting the timestamp to default when the flag is = 0.

**Comment by weliem** [comment]
Fixed in a6b072d
