### ISSUE TITLE
Discover the same peripheral multiple times

### ISSUE THREAD

**Issue by gmontemayor1987** [weliem/blessed-android#194]
This is not a bug, this is more like a question. I send it first to Stackoverflow: https://stackoverflow.com/questions/77902075/discover-the-same-peripheral-multiple-times-in-blessed-android

In Swift, I start scanning peripherals with:

central.scanPeripherals(withServices: nil, options: [CBCentralManagerScanOptionAllowDuplicatesKey : self.allowDuplicateScan])

It is allowing multiple discoveries of the same peripheral. So, the delegate didDiscover function is called every time the peripheral is seen.

Now, I want to do exactly the same in Android (using blessed-android). I'm calling central.scanForPeripheralsWithServices(services) to discover new services. However, the onDiscoveredPeripheral callback it's only called once per peripheral. So the question is if it is possible to have the same behavior than Swift?

**Comment by weliem** [comment]
The standard behavior is that you should see onDeviceFound be called multiple times. What makes you think that it is not working? Can you share relevant code and logs?
