### ISSUE TITLE
MIgration guide to blessed-kotlin

### ISSUE THREAD

**Issue by ceduliocezar** [weliem/blessed-android#197]
Hi @weliem ,

Im looking for a guide to migrate to blessed-kotlin, is there any guide around?

I wonder how much the api changed, if it would be considered a major breaking change.

Thanks for this amazing library :)

**Comment by ceduliocezar** [comment]
Additionally are the two library 1:1 port already?

**Comment by weliem** [comment]
I don't have a guide, but it is fairly easy to migrate. one or two calls have a new, but better, name. The parser has been split in a pure parser and bytearray builder. The rest is identical.
