### ISSUE TITLE
peripheral.getName() == null

### ISSUE THREAD

**Issue by WanManito** [weliem/blessed-android#199]
Hello, I would like to ask, when I call "central. getPeripheral()" to obtain "BluetoothPeripheral()" and then call "central. connectPeripheral()" to connect, is it normal for the callback "onConnectedPeripheral()" and other callbacks to have "perimeter. getName()" equal to NULL? 
I seem to have found a similar issue, and do I need to use "autoConnectPeripheral()" or search again to connect again to avoid this problem?

**Comment by weliem** [comment]
yes, it happens. Not all peripherals have a name....
