### ISSUE TITLE
Scan return null

### ISSUE THREAD

**Issue by animecomico** [weliem/blessed-android#20]
Hi, Whe Scan always return name of device null and no connect.

Test in Android 9

**Comment by weliem** [comment]
Can you share some code so that I can understand what you are doing?

**Comment by animecomico** [comment]
Hi,
I modidy the BluetoothHandler for my device
package com.scarab.blespot_2;

import android.bluetooth.BluetoothGattCharacteristic;
import android.bluetooth.le.ScanResult;
import android.content.Context;
import android.content.Intent;
import android.os.Handler;

import java.util.Calendar;
import java.util.Date;
import java.util.UUID;

import com.scarab.manblue.BluetoothBytesParser;
import com.scarab.manblue.BluetoothCentral;
import com.scarab.manblue.BluetoothCentralCallback;
import com.scarab.manblue.BluetoothPeripheral;
import com.scarab.manblue.BluetoothPeripheralCallback;

import timber.log.Timber;

import static android.bluetooth.BluetoothGatt.CONNECTION_PRIORITY_HIGH;
import static com.scarab.manblue.BluetoothBytesParser.bytes2String;
import static com.scarab.manblue.BluetoothPeripheral.GATT_SUCCESS;


public class BluetoothHandler {
    // Spot AG Service
    private static final UUID SPOT_AG_SERVICE = UUID.fromString("00008601-1D13-34F8-B855-418FFE6B82E3");
    private static final UUID SECURITY_CHARACTERISTIC_UUID = UUID.fromString("00008602-1D13-34F8-B855-418FFE6B82E3");
    private static final UUID STATUS_CHARACTERISTIC_UUID = UUID.fromString("00008603-1D13-34F8-B855-418FFE6B82E3");
    private static final UUID CONTROL_CHARACTERISTIC_UUID = UUID.fromString("00008604-1D13-34F8-B855-418FFE6B82E3");
    private static final UUID DATA_CHARACTERISTIC_UUID = UUID.fromString("00008605-1D13-34F8-B855-418FFE6B82E3");
    private static final UUID CLI_CHARACTERISTIC_UUID = UUID.fromString("00008606-1D13-34F8-B855-418FFE6B82E3");
    //FANSTELS ONLY TEST
    private static final UUID UART_FANSTEL_UUID = UUID.fromString("6e400001-b5a3-f393-e0a9-e50e24dcca9e");
    private static final UUID UART_RX_CHARACTERISTIC_UUID = UUID.fromString("6e400002-b5a3-f393-e0a9-e50e24dcca9e");
    private static final UUID UART_TX_CHARACTERISTIC_UUID = UUID.fromString("6e400003-b5a3-f393-e0a9-e50e24dcca9e");
    //
    private Context context;
    private BluetoothCentral central;
    private Handler handler = new Handler();
    private int currentTimeCounter = 0;
    private static BluetoothHandler instance = null;
    //
    private final BluetoothPeripheralCallback peripheralCallback = new BluetoothPeripheralCallback() {
        @Override
        public void onServicesDiscovered(final BluetoothPeripheral peripheral) {
            Timber.i("discovered services");

            // Request a new connection priority
            peripheral.requestConnectionPriority(CONNECTION_PRIORITY_HIGH);

            // Turn on notifications for Data Characteristic
            if(peripheral.getService(DATA_CHARACTERISTIC_UUID) != null) {
                peripheral.setNotify(peripheral.getCharacteristic(SPOT_AG_SERVICE, DATA_CHARACTERISTIC_UUID), true);
            }

            // Turn on notifications for Status Characteristic
            if(peripheral.getService(STATUS_CHARACTERISTIC_UUID) != null) {
                peripheral.setNotify(peripheral.getCharacteristic(SPOT_AG_SERVICE, STATUS_CHARACTERISTIC_UUID), true);
            }
            // For TEST with UART Fanstel
            // Turn on notification for Health Thermometer Service
            if(peripheral.getService(UART_TX_CHARACTERISTIC_UUID) != null) {
                Timber.i("discovered services UART TX");
                peripheral.setNotify(peripheral.getCharacteristic(UART_FANSTEL_UUID, UART_TX_CHARACTERISTIC_UUID), true);
            }
        }

        @Override
        public void onNotificationStateUpdate(BluetoothPeripheral peripheral, BluetoothGattCharacteristic characteristic, int status) {
            if( status == GATT_SUCCESS) {
                if(peripheral.isNotifying(characteristic)) {
                    Timber.i("SUCCESS: Notify set to 'on' for %s", characteristic.getUuid());
                } else {
                    Timber.i("SUCCESS: Notify set to 'off' for %s", characteristic.getUuid());
                }
            } else {
                Timber.e("ERROR: Changing notification state failed for %s", characteristic.getUuid());
            }
        }

        @Override
        public void onCharacteristicWrite(BluetoothPeripheral peripheral, byte[] value, BluetoothGattCharacteristic characteristic, int status) {
            if( status == GATT_SUCCESS) {
                Timber.i("SUCCESS: Writing <%s> to <%s>", bytes2String(value), characteristic.getUuid().toString());
            } else {
                Timber.i("ERROR: Failed writing <%s> to <%s>", bytes2String(value), characteristic.getUuid().toString());
            }
        }

        @Override
        public void onCharacteristicUpdate(BluetoothPeripheral peripheral, byte[] value, BluetoothGattCharacteristic characteristic, int status) {
            if(status != GATT_SUCCESS) return;
            UUID characteristicUUID = characteristic.getUuid();
            BluetoothBytesParser parser = new BluetoothBytesParser(value);

            if (characteristicUUID.equals(SECURITY_CHARACTERISTIC_UUID)) {
                Timber.d("%s", "Change on Security Characteristic");
            }
            else if(characteristicUUID.equals(STATUS_CHARACTERISTIC_UUID)) {
                Timber.d("%s", "Change on Status Characteristic");
            }
            else if(characteristicUUID.equals(CONTROL_CHARACTERISTIC_UUID)) {
                Timber.d("%s", "Change on Control Characteristic");
            }
            else if(characteristicUUID.equals(DATA_CHARACTERISTIC_UUID)) {
                Timber.d("%s", "Change on Data Characteristic");
            }
            else if(characteristicUUID.equals(CLI_CHARACTERISTIC_UUID)) {
                Timber.d("%s", "Change on Data Characteristic");
            }//For Test UART
            else if(characteristicUUID.equals(UART_TX_CHARACTERISTIC_UUID)) {
                Timber.d("%s", "Change on TX Fanstel Characteristic");
            }
        }
    };
    //
    private final BluetoothCentralCallback bluetoothCentralCallback = new BluetoothCentralCallback() {
        @Override
        public void onConnectedPeripheral(final BluetoothPeripheral peripheral) {
            super.onConnectedPeripheral(peripheral);
            Timber.i("connected to '%s'", peripheral.getName());
        }

        @Override
        public void onConnectionFailed(final BluetoothPeripheral peripheral, int status) {
            super.onConnectionFailed(peripheral, status);
            Timber.e("connection '%s' failed with status %d", peripheral.getName(), status);
        }

        @Override
        public void onDisconnectedPeripheral(final BluetoothPeripheral peripheral, int status) {
            super.onDisconnectedPeripheral(peripheral, status);
            Timber.i("disconnected '%s' with status %d", peripheral.getName(), status);

            // Reconnect to this device when it becomes available again
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    central.autoConnectPeripheral(peripheral, peripheralCallback);
                }
            }, 5000);
        }

        @Override
        public void onDiscoveredPeripheral(final BluetoothPeripheral peripheral, ScanResult scanResult) {
            super.onDiscoveredPeripheral(peripheral, scanResult);
            Timber.i("Found peripheral '%s'", peripheral.getName());
            central.stopScan();
            central.connectPeripheral(peripheral, peripheralCallback);
        }
    };
//    //
//    public static synchronized BluetoothHandler getInstance(Context context) {
//        if (instance == null) {
//            instance = new BluetoothHandler(context.getApplicationContext());
//        }
//        return instance;
//    }
//    //
//    private BluetoothHandler(Context context){
//        this.context = context;
//        // Create BluetoothCentral
//        central = new BluetoothCentral(context, bluetoothCentralCallback, new Handler());
//
//        // Scan for peripherals with a certain service UUIDs
//        central.startPairingPopupHack();
//        central.scanForPeripheralsWithServices(new UUID[]{SPOT_AG_SERVICE,
//                STATUS_CHARACTERISTIC_UUID,
//                UART_FANSTEL_UUID});
//    }
    public BluetoothHandler(Context context){
        this.context = context;
        central = new BluetoothCentral(context, bluetoothCentralCallback, new Handler());
    }

    public void onScan(){
        // Scan for peripherals with a certain service UUIDs
        central.startPairingPopupHack();
        central.scanForPeripherals();
        Timber.i("Start Scan");
//        central.scanForPeripheralsWithServices(new UUID[]{SPOT_AG_SERVICE,
//                STATUS_CHARACTERISTIC_UUID,
//                UART_FANSTEL_UUID});
    }

    public void offScan(){
        central.stopScan();
        Timber.i("Stop Scan");
    }
}

**Comment by animecomico** [comment]
This is the MainActivity

package com.scarab.blespot_2;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;

import android.Manifest;
import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.scarab.manblue.BuildConfig;

import timber.log.Timber;

public class MainActivity extends AppCompatActivity {

    private TextView txtDbg;
    private  Button btnScan;
    private  Button btnConnect;
    private  Button btnTest;
    private BluetoothHandler blueman;
    //
    String[] PERMISSIONS = {
            Manifest.permission.BLUETOOTH,
            Manifest.permission.BLUETOOTH_ADMIN,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.UPDATE_DEVICE_STATS
    };
    int PERMISSION_ALL = 1;

    boolean isDebug = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (!hasPermissions(this, PERMISSIONS)) {
            ActivityCompat.requestPermissions(this, PERMISSIONS, PERMISSION_ALL);
        }

        isDebug = ((this.getApplicationInfo().flags &
                ApplicationInfo.FLAG_DEBUGGABLE) != 0);

        if(isDebug){
            Timber.plant(new Timber.DebugTree());
        }
        //
        blueman = new BluetoothHandler(getApplicationContext());

        txtDbg = findViewById(R.id.textView);
        txtDbg.setMovementMethod(new ScrollingMovementMethod());
        //
        btnScan = findViewById(R.id.button);
        btnConnect = findViewById(R.id.button2);
        btnTest = findViewById(R.id.button3);
        //
        btnScan.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(btnScan.getText().toString().equals("SCAN")){
                    txtDbg.append("Scan\n");
                    //btnScan.setText("STOP SCAN");
                    blueman.onScan();
                }else{
                    txtDbg.append("Stop Scan\n");
                    btnScan.setText("SCAN");
                    blueman.offScan();
                }
            }
        });
        //
        btnConnect.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                txtDbg.append("Connect\n");
            }
        });
        //
        btnTest.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                txtDbg.append("Test\n");
            }
        });
    }

    public static boolean hasPermissions(Context context, String... permissions) {
        if (context != null && permissions != null) {
            for (String permission : permissions) {
                if (ActivityCompat.checkSelfPermission(context, permission) != PackageManager.PERMISSION_GRANTED) {
                    return false;
                }
            }
        }
        return true;
    }
}

**Comment by weliem** [comment]
Well, there are a couple of strange things in your code:

1.  You start a scan **without any filtering** whatsoever. So you will get many results and will see every bluetooth peripheral around you. Many of them will be mobile phones that don't have a name and will give you 'null' as the name.
2. On the **first result** you stop the scan, and you then connect to the first device you find. This is probably not the peripheral you are interested in...

So my suggestion would be to start a scan that will only find your peripheral. I don't know your device but you could try scanning with a service UUID filter that would only let your peripheral through. Something like this:

```
public void onScan(){
    // Scan for peripherals with a certain service UUIDs
    central.startPairingPopupHack();
     central.scanForPeripheralsWithServices(new UUID[]{SPOT_AG_SERVICE});
    Timber.i("Start Scan");
```

That would start a scan and only let through peripherals that have the service SPOT_AG_SERVICE.

**Comment by weliem** [comment]
Any update on this issue?
