### ISSUE TITLE
ble scan for unknown devices

### ISSUE THREAD

**Issue by oliexdev** [weliem/blessed-android#3]
it would be great if you could add a 4th scan method to scan for unknown devices to discover the hardware address or the services of each Bluetooth device. What do you think?

**Comment by weliem** [comment]
If you do `scanForPeripheralsWithServices(null)` you will get all scan results without any filtering.

Is that what you mean?

**Comment by oliexdev** [comment]
thanks didn't know that. Maybe something for the documentation?

**Comment by weliem** [comment]
I think you are right in that this is a bit confusing. So I just added as new method scanForPeripherals().
