### ISSUE TITLE
System PIN dialog not showing

### ISSUE THREAD

**Issue by DaxeshV** [weliem/blessed-android#62]
BLE PIN checking; the system PIN dialog when the pairing request is happen missing. its need for security reason else anyone can connect BLE

**Comment by weliem** [comment]
Showing the system PIN dialog is being done by Android, and not by the Blessed library.

**Comment by DaxeshV** [comment]
Yes. But when i using library and make request for connect it connect without PIN.

**Comment by DaxeshV** [comment]
Also is it support auto connect BLE when device back in range?

**Comment by weliem** [comment]
The bluetooth device needs to send a message that it requires a PIN code. Otherwise the PIN dialog will not appear and apparently your device does not do that....so it is a problem with your device

**Comment by DaxeshV** [comment]
So its automatic process right. for showing system dialog i need to add any code?

**Comment by weliem** [comment]
No nothing needed from the app side...
