### ISSUE TITLE
Example app functionality 

### ISSUE THREAD

**Issue by S8enson** [weliem/blessed-android#64]
Not sure if I have done something wrong but the included app example has no functionality when installed on my device. It just sits on the "Waiting for measurement.." screen indefinitely, is this intentional?

**Comment by weliem** [comment]
The example app will scan for and connect to devices that have the Thermometer, HeartRate, Weight, Blood-pressure, or PulseOx service. So if you don't have a device that has any of those services, it wont do anything indeed...

But nonetheless, it shows you how to use the library in your application.
