### ISSUE TITLE
Continuous Read for PulseOx

### ISSUE THREAD

**Issue by tassociates** [weliem/blessed-android#81]
Does your library and example support continuous reading of PulseOx data from the Masimo MightySat?  In playing with the sample app, it appears it will read it only if the mightysat is disconnected on the Spot Measurement but does not pick up continuous profile?

**Comment by weliem** [comment]
The Masimo doesn't support the continuous pulseox characteristic. It only has the spot measurement one.

It is possible to get continuous pulseox but then you need to implement their proprietary protocol. Which obviously is not part of the example app....
