### ISSUE TITLE
No gradle information is provided

### ISSUE THREAD

**Issue by Obaid-ur-Rehman** [weliem/blessed-android#82]
The documentation should indicate how to sync gradle with this library. This basic and most important part is missing.

**Comment by wrzosdev** [comment]
Hi Obaid, there is such information actually, it's simply kind of not exposed 
![image](https://user-images.githubusercontent.com/29088102/115098400-33b9e700-9f30-11eb-991b-cb5ba35cac33.png)
The library is using JitPack (check it out if you haven't yet!)

**Comment by weliem** [comment]
Indeed, just click on the badge and you'll find the instructions there
