### ISSUE TITLE
Library silently fails when required permissions are not granted

### ISSUE THREAD

**Issue by sylque** [weliem/blessed-android#87]
You need the `location` permission for Blessed to work. Maybe the doc should say something about it and the library should throw an exception in case of missing permission.

**Comment by weliem** [comment]
There are quite a lot of permissions needed with regards to using Bluetooth on Android. I have stayed away from throwing exceptions for missing permission but I will rethink this one over again. Up to now I simply logged the absence of a permission....

**Comment by martijnvanwelie** [comment]
Fixed in latest commit. A SecurityException wil be thrown in case of missing permission
