### ISSUE TITLE
Scan with pendingintent

### ISSUE THREAD

**Issue by fvisticot** [weliem/blessed-android#9]
Is your library able to manage scanning with a pending intent ?

[https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(java.util.List%3Candroid.bluetooth.le.ScanFilter%3E,%20android.bluetooth.le.ScanSettings,%20android.app.PendingIntent)](url)

[https://stackoverflow.com/questions/52918754/android-ble-scanning-with-pendingintent](url)

**Comment by weliem** [comment]
Currently it is not supported. I have no plans to add it on the short term...
