### ISSUE TITLE
Feature request: support for service 16-bits and 32-bits UUIDs

### ISSUE THREAD

**Issue by steph643** [weliem/blessed-android#90]
It seems this library only supports 128-bits UUIDs for services. 
On one side, this sounds like a reasonable choice: I guess 16-bits and 32-bits UUIDs are more for big companies willing to pay for officially registered UUIDs, so not the majority of users. 
But on the other side, 128-bits UUIDs seem to be quite difficult to advertise (you can usually fit only one in the advertisement mechanism), so it is very tempting to use "unofficial" 16-bits and 32-bits UUIDs. 
Also, there might be a power consumption advantage to 16-bits and 32-bits UUIDs.

**Comment by weliem** [comment]
The library supports peripherals that only advertise 16bit uuids. However, when you pass a UUID you first have to convert it to a full 128 bit UUID. There is no such thing as a 16 uuid, it is just a short-hand notation for a normal full 128 bit uuid.
