### ISSUE TITLE
Callbacks location

### ISSUE THREAD

**Issue by steph643** [weliem/blessed-android#91]
`onConnectedPeripheral()` and `onDisconnectedPeripheral()` are in `BluetoothCentralManagerCallback`. It would sound more logical to me to put them in `BluetoothPeripheralCallback` (as `onConnected()` and `onDisconnected()`).

**Comment by weliem** [comment]
Actually, when you have to deal with multiple peripherals being connected at the same time, it is much more convenient to have it all in one place. You can then deal with peripheral connections, errors and disconnects in a central place and avoid code duplications.

It is not for nothing that CoreBluetooth (by Apple) is also doing it like this...

**Comment by steph643** [comment]
Code duplications? Seriously?
