### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by RanaEnnabah** [weliem/blessed-android#92]
I currently install the lib using:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.github.weliem:blessed-android:2.0.5'
    //...
}
```

.. however, I think there's a better way to install it from jcenter (or any other source) instead of GitHub. Right?

Thanks :)

**Comment by weliem** [comment]
What you are doing looks fine to me. The library is hosted on Jitpack indeed

So I don't understand your problem. Please elaborate
