### ISSUE TITLE
Multiple gatt object in memory - Help 

### ISSUE THREAD

**Issue by droideveloper1996** [weliem/blessed-android#93]
Hi, 

I was developing a BLE application and I got through your guide on Medium and that was fantastic. I was struck while developing ble notification showing some weird notification issue.

# I summarize my problem in two categories when bonding is removed or lost and when the connection is reattempted.

onCharacteristicChanged called on multiple GATT objects when reconnect without closing the GATT(previous). Looks like gattConnect() return a new instance each time I reconnect, if I close the GATT on the onConnectionStateChange() then it works for me I don't get multiple notifications, but at the same time, I don't get a notification when I remove bonding and bond the device again.

But when I don't close GATT object, I get notified but this time I  get more than one notification.

I did go through BluetoothGatt Class looks like it returns new GATT object on reconnection. I don't understand how to handle this scenario. I don't see any way to unregister the callback or destroy the object method.

Catch: Upon looking at your library I see that you played with BluetoothGatt class and manipulated using reflection.
@weliem Is it the correct way of doing it? or needs a complete rewrite.

public class BackgroundBluetoothServices extends Service implements BluetoothAdapter.LeScanCallback {

    public static final String NOTIFICATION_CHANNEL_NAME = "service_notification_channel";
    public Random random;
    private static final String TAG = "BluetoothBackgroundService";
    private final IBinder mBinder = new BoundServiceBinder();
    private Timer timer;
    private BluetoothAdapter mBluetoothAdapter;
    private BluetoothManager bluetoothManager;
    private BluetoothGatt activeBtGatt;
    private BluetoothGatt passiveBtGatt;
    private BleConnectionManager mConnectionManager;
    public static String PRIMARY_DEVICE_NAME = "";
    public static String PRIMARY_DEVICE_ADDRESS = "";
    public static String SECONDARY_DEVICE_NAME = "";
    public static String SECONDARY_DEVICE_ADDRESS = "";
    private ProgressDialog progressDialog;
    HashMap<String, Boolean> globalRoomMap;
    private StringBuilder stringBuilder;
    public BleResponseInterface responseInterface;
    private Context mCtx;

    public boolean isNotificationEnabled = false;
    public static final String BRAND_OPPO = "OPPO";
    public static final String BRAND_SAMSUNG = "samsung";
    public static final String BRAND_REALME = "REALME";

    private BluetoothGatt oldGatt;
    private BluetoothGatt newGatt;
    private Handler bleHandler;
    private String RESTRICTED_DEVICE;

    @Override
    public IBinder onBind(Intent intent) {
        return mBinder;
    }

    @Override
    public void onCreate() {
        super.onCreate();
//        this.globalRoomMap = App.getRooms();
        this.globalRoomMap = new HashMap<>();
        SharedPreferencesManager sharedPreferencesManager = new SharedPreferencesManager(getApplicationContext());
        int position=sharedPreferencesManager.getItemPosition();
        RESTRICTED_DEVICE=App.deviceNames[position];
        Log.d(TAG, "onCreate: Default Device, "+RESTRICTED_DEVICE);
        globalRoomMap.put(RESTRICTED_DEVICE,false);
        stringBuilder = new StringBuilder();
        createNotificationChannel();
        timer = new Timer();
        random = new Random();
        mBluetoothAdapter = getBTService();
        scanLeDevice(true);
        mConnectionManager = BleConnectionManager.getInstance();
        Log.d(TAG, "onCreate: Instance" + this);
        Context context;
        this.progressDialog = new ProgressDialog(getApplicationContext());
        IntentFilter intentFilter = new IntentFilter();
        intentFilter.addAction(ACTION_BOND_STATE_CHANGED);
        getApplicationContext().registerReceiver(bondStateReceiver, intentFilter);
        bleHandler=new Handler(Looper.getMainLooper());

    }

    public BluetoothAdapter getBTService() {
        BluetoothManager btManager = (BluetoothManager) getApplicationContext().getSystemService(Context.BLUETOOTH_SERVICE);
        mBluetoothAdapter = (BluetoothAdapter) btManager.getAdapter();
        return mBluetoothAdapter;
    }

    /**
     * @param enable
     */
    public void scanLeDevice(final boolean enable) {
        if (enable) {
            startBLEscan();
        } else {
            stopBLEscan();
        }
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        /**
         * Do Bluetooth scanning here
         */
        Intent _i = new Intent(getApplicationContext(), MainActivity.class);
        PendingIntent pendingIntent = PendingIntent.getActivity(getApplicationContext(), 0, _i, 0);
        NotificationCompat.Builder builder = new NotificationCompat.Builder(getApplicationContext(), NOTIFICATION_CHANNEL_NAME);
        builder.setContentTitle("BLE Scanner is Running")
                .setSmallIcon(R.mipmap.ic_launcher_round)
                .setContentIntent(pendingIntent)
                .setContentText("Background");

        if (!isBluetoothSupported()) {
            Toast.makeText(this, "Not supported", Toast.LENGTH_SHORT).show();
            stopSelf();
        } else {
            if (mBluetoothAdapter != null && mBluetoothAdapter.isEnabled()) {

                startBLEscan();
            } else {
                stopSelf();
            }
        }

        startForeground(1, builder.build());
        return START_STICKY;
    }

    private boolean isPrimaryConnectionDone = false;
    private boolean isSecondaryConnectionDone = false;

    @Override
    public void onLeScan(BluetoothDevice device, int rssi, byte[] scanRecord) {

        if (globalRoomMap.size() == 0) {
            scanLeDevice(false);
            return;
        }

        if (device != null && device.getName() != null) {
            Log.d(TAG, "onLeScan: " + globalRoomMap);
            Log.d(TAG, "Name: " + device.getName() + "Address: " + device.getAddress() + "RSSI: " + rssi);
            if (rssi > -90 && rssi < -1 && globalRoomMap.containsKey(device.getName()) || globalRoomMap.containsKey(device.getAddress())) {
//                Log.d(TAG, "onLeScan: ");("Automate service BLE device in range: " + device.getName() + " " + rssi);
                if (!isPrimaryConnectionDone && !globalRoomMap.get(device.getAddress())) {
                    isPrimaryConnectionDone = true;
                    globalRoomMap.put(device.getAddress(), true);
                    Log.d(TAG, "onLeScan: "+RESTRICTED_DEVICE);
                    if (device.getName().equals(RESTRICTED_DEVICE) || device.getAddress().equals(RESTRICTED_DEVICE)) {
                        Log.d(TAG, "onLeScan: Making Primary Connection Device Hardcoded to 84:24");
                        makePrimaryConnection(device);
                    }
                }

                if (activeBtGatt != null) {
                    stopBLEscan();
                }

                Log.d(TAG, "onLeScan: primaryCon object " + activeBtGatt);
            } else {
                Log.e("Device Scan Activity", device.getAddress() + " " + "BT device is still too far - not connecting");
            }
        }
    }

    @Override
    public void onDestroy() {
        stopBLEscan();
        super.onDestroy();

        if (activeBtGatt != null) {
            activeBtGatt.disconnect();
            activeBtGatt.close();
            activeBtGatt = null;
        }
        if (passiveBtGatt != null) {
            passiveBtGatt.disconnect();
            passiveBtGatt.close();
            passiveBtGatt = null;
        }

        getApplicationContext().unregisterReceiver(bondStateReceiver);
    }

    public class BoundServiceBinder extends Binder {

        public BackgroundBluetoothServices getInstance() {
            return BackgroundBluetoothServices.this;
        }
    }

    public boolean isBluetoothSupported() {
        return this.getPackageManager().hasSystemFeature(PackageManager.FEATURE_BLUETOOTH_LE);
    }

    public void startBLEscan() {
        mBluetoothAdapter.startLeScan(this);
    }

    public void stopBLEscan() {
        mBluetoothAdapter.stopLeScan(this);
    }

    public void createNotificationChannel() {

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel notificationChannel = new NotificationChannel(NOTIFICATION_CHANNEL_NAME, "Example Channel", NotificationManager.IMPORTANCE_DEFAULT);
            NotificationManager manager = getSystemService(NotificationManager.class);
            manager.createNotificationChannel(notificationChannel);

        }
    }

    private BluetoothGattCallback bleGattCallback = new BluetoothGattCallback() {

        @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
        @Override
        public synchronized void onConnectionStateChange(final BluetoothGatt gatt, int status, int newState) {
            super.onConnectionStateChange(gatt, status, newState);
            writeLine("Automate service connection state: " + newState);
            gatt.requestMtu(512);

            if (newState == android.bluetooth.BluetoothProfile.STATE_CONNECTED) {

                if (activeBtGatt != null || passiveBtGatt != null) {
//                    HomeFragment.hideProgressDialogue();
                }
                writeLine("Automate service connection state: STATE_CONNECTED");
                Log.v("BLEService", "BLE Connected now discover services");
                Log.v("BLEService", "BLE Connected");
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        writeLine("Automate service go for discover services");
                        gatt.discoverServices();
                    }
                }).start();
            } else if (newState == BluetoothProfile.STATE_DISCONNECTING) {

                Log.d(TAG, "onConnectionStateChange: Started Disconnecting from device");

            } else if (newState == BluetoothProfile.STATE_DISCONNECTED || status == 8) {
                Log.d(TAG, "onConnectionStateChange: Ble device is disconnected");
                Log.d(TAG, "Started Scanning for new Devices");
                gatt.close();
                isNotificationEnabled = false;
                Handler h = new Handler(getApplicationContext().getMainLooper());
                h.post(new Runnable() {
                    @Override
                    public void run() {
                        if (Utils.isAppOnForeground(mCtx))
                            HomeFragment.showProgressDialogue("Attempting Connection...", "Please wait...");
                    }
                });
                startBLEscan();
                Log.d(TAG, "Scanning Completed for new Devices");
                if (gatt.getDevice().getAddress().equals(PRIMARY_DEVICE_ADDRESS)) {
                    isPrimaryConnectionDone = false;
                    globalRoomMap.put(RESTRICTED_DEVICE, false);
                    Log.d(TAG, "onConnectionStateChange: -----------------------------Handling Primary Connection ---------------------------------");
                    Log.d(TAG, "onConnectionStateChange: Making active gatt to  null");
                    activeBtGatt = null;
//                    Log.d(TAG, "onConnectionStateChange: Active connection set to secondary");
                    mConnectionManager.setActiveConnection(passiveBtGatt);
                    Log.d(TAG, "onConnectionStateChange: Primary connection set to null");
                    mConnectionManager.setPrimaryConnection(null);
                    Log.d(TAG, "onConnectionStateChange: -----------------------------End of Handling Primary Connection ---------------------------------");

                }
            }
        }

        @Override
        public void onServicesDiscovered(final BluetoothGatt gatt, int status) {
            super.onServicesDiscovered(gatt, status);
            if (status == BluetoothGatt.GATT_SUCCESS) {

                writeLine("Automate service discover service: GATT_SUCCESS");
                Log.v("BLEService", "BLE Services onServicesDiscovered");
                BleConnectionManager ins = BleConnectionManager.getInstance();
                if (gatt.getDevice().getAddress().equals(PRIMARY_DEVICE_ADDRESS)) {
                    Log.d(TAG, "onServicesDiscovered: Primary Device Services Discovered");
                    if (ins != null && ins.getPrimaryConnection() != null) {
                        List<BluetoothGattService> services = ins.getPrimaryConnection().getServices();
                        for (int i = 0; i < services.size(); i++) {
                            BluetoothGattService service = services.get(i);
                            Log.d(TAG, "onServicesDiscovered: " + service.getUuid().toString());
                            if (service.getUuid().toString().equals(Constants.BLE_SERVICE_ID)) {

                                List<BluetoothGattCharacteristic> characteristics = service.getCharacteristics();
                                for (int k = 0; k < characteristics.size(); k++) {
                                    BluetoothGattCharacteristic _characteristic = characteristics.get(k);
                                    Log.d("MainActivity", "onClick: " + characteristics.get(k).getUuid().toString());
                                    if (hasWriteProperty(_characteristic.getProperties()) != 0) {
                                        ins.setPrimaryWriteCharacteristic(_characteristic);
                                        Log.d(TAG, "onServicesDiscovered: Primary Write Characteristic " + _characteristic);
                                    }

                                    if (hasNotifyProperty(_characteristic.getProperties()) != 0) {
                                        Log.d(TAG, "run: Enabling Primary Notification");
                                        ins.setPrimaryNotifyCharacteristic(_characteristic);
                                        //Enable Notification onReadCharacteristic()
                                    }
                                    if (hasReadProperty(_characteristic.getProperties()) != 0) {
                                        new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
                                            @Override
                                            public void run() {
                                                ins.setPrimaryReadCharacteristic(_characteristic);
                                                ins.getPrimaryConnection().readCharacteristic(_characteristic);
                                                Log.d(TAG, "onServicesDiscovered: Primary Read Characteristic " + _characteristic);
                                            }
                                        }, 2000);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if (status == BluetoothGatt.GATT_FAILURE) {
                Log.e(TAG, "Service discovery failed");
                gatt.close();
                return;
            }
        }

        @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
        public void setCharacteristicNotification(BluetoothGatt mBluetoothGatt, BluetoothGattCharacteristic characteristic, boolean enabled) {
            if (mBluetoothAdapter == null || mBluetoothGatt == null) {
                Log.w(TAG, "BluetoothAdapter not initialized");
                return;
            }
            Log.d("Check", "setCharacteristicNotification");

            mBluetoothGatt.setCharacteristicNotification(characteristic, enabled);
            BluetoothGattDescriptor descriptor = characteristic.getDescriptor(
                    UUID.fromString(getString(R.string.CLIENT_CHARACTERISTIC_CONFIG)));

            if (enabled) {
                descriptor.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);
            } else {
                descriptor.setValue(BluetoothGattDescriptor.DISABLE_NOTIFICATION_VALUE);
            }
            mBluetoothGatt.writeDescriptor(descriptor);
            isNotificationEnabled = enabled;

        }

        @Override
        public void onCharacteristicRead(BluetoothGatt gatt, BluetoothGattCharacteristic
                characteristic, int status) {
//            super.onCharacteristicRead(gatt, characteristic, status);
            final byte[] data = characteristic.getValue();
            String str = new String(data);
            Log.d(TAG, "Characteristic Read From Device: " + str.substring(8, 9));
            //  if (str.substring(8, 9).equals("1")) {
            Log.d(TAG, "onCharacteristicRead: Device is authenticated");
            Log.d(TAG, "onCharacteristicRead: -----------------Check Begins------------------");
            Log.d(TAG, "onCharacteristicRead: Enabling Notification");

            List<BluetoothGattService> serviceArrayList = gatt.getServices();
            for (int i = 0; i < serviceArrayList.size(); i++) {
                BluetoothGattService service = serviceArrayList.get(i);
                if (service.getUuid().toString().equals(Constants.BLE_SERVICE_ID)) {
                    List<BluetoothGattCharacteristic> characteristicList = service.getCharacteristics();
                    for (BluetoothGattCharacteristic gattCharacteristic : characteristicList) {
                        if (Utils.hasNotifyProperty(gattCharacteristic.getProperties()) != 0) {
                            new Handler(Looper.getMainLooper()).postDelayed(
                                    new Runnable() {
                                        @Override
                                        public void run() {
                                            Log.d(TAG, "run: Enabled Primary Notification after authentication check ");
                                            if (!isNotificationEnabled) {
                                                setCharacteristicNotification(gatt, gattCharacteristic, true);
                                                new Handler().postDelayed(new Runnable() {
                                                    @Override
                                                    public void run() {
                                                        ((MainActivity) mCtx).hideLoadingConfiguration();
                                                        HomeFragment.hideProgressDialogue();
                                                    }
                                                }, 25000);
                                            }
                                        }
                                    }
                                    , 2000);
                        }
                    }
                }

            }
            // }

        }

        @Override
        public void onCharacteristicChanged(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic) {
            super.onCharacteristicChanged(gatt, characteristic);

            Log.d(TAG, "---------------------------------------------");

            final byte[] data = new byte[characteristic.getValue().length];
            System.arraycopy(characteristic.getValue(), 0, data, 0, characteristic.getValue().length);
            String str = new String(data);
            Handler handler=new Handler(Looper.getMainLooper());
            handler.post(new Runnable() {
                @Override
                public void run() {
                    if (data != null && data.length > 0) {
                        String handledResponse = str.replaceAll("[^\\p{ASCII}]", "");
                        if (handledResponse.length() == 200) {
                            stringBuilder.append(handledResponse);
                        }
                        if (handledResponse.length() < 200) {
                            stringBuilder.append(handledResponse);
                            String pp = stringBuilder.toString().replaceAll("[^\\p{ASCII}]", "");
                            Log.d(TAG, "Complete Data Length " + stringBuilder.toString().length());
                            responseInterface.onDataReceived(pp);
                            stringBuilder = new StringBuilder();
                            Log.d(TAG, "----------------End Of Response----------------------");
                        }
                    }
                }
            });

        }
    };

    private void writeLine(final String message) {

        Log.d(TAG, "writeLine: message " + message);
    }

    private void makePrimaryConnection(BluetoothDevice device) {
        PRIMARY_DEVICE_ADDRESS = device.getAddress();
        //Here if you use Looper.getMainLooper() it will stop getting callback and give internal exception fail to register //callback
        new Handler(getApplicationContext().getMainLooper()).post(new Runnable() {
            @Override
            public void run() {
                Log.d(TAG, "run: Trying to Connect to Device Conn1 State " + activeBtGatt);
                activeBtGatt = device.connectGatt(getApplicationContext(), false, bleGattCallback);
                mConnectionManager.setPrimaryConnection(activeBtGatt);
                    mConnectionManager.setActiveConnection(activeBtGatt);
                    Log.d(TAG, "onLeScan btGatt value returning from connectGatt conn1 " + activeBtGatt);
            }
        });
    }

    public interface BleResponseInterface {
        public void onDataReceived(String object);
    }

    public void registerClient(Context mCtx) {
        this.responseInterface = (BleResponseInterface) mCtx;
        this.mCtx = mCtx;
        if (App.getRooms().size() > 0) {
            ((MainActivity) mCtx).showLoadingConfiguration();
        }
    }

    final BroadcastReceiver bondStateReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            final String action = intent.getAction();
            final BluetoothDevice device = intent.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);

            if (action == null)
                return;

            // Take action depending on new bond state
            if (action.equals(ACTION_BOND_STATE_CHANGED)) {
                final int bondState = intent.getIntExtra(EXTRA_BOND_STATE, ERROR);
                final int previousBondState = intent.getIntExtra(BluetoothDevice.EXTRA_PREVIOUS_BOND_STATE, -1);

                switch (bondState) {
                    case BOND_BONDING:
                        // Bonding started
                        Log.d(TAG, "onReceive: BONDING");

                        break;
                    case BOND_BONDED:
                        // Bonding succeeded
                        bleHandler.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                Log.d(TAG, "run: Reading device: " + mConnectionManager.getPrimaryReadCharacteristic());
                                mConnectionManager.getPrimaryConnection().readCharacteristic(mConnectionManager.getPrimaryReadCharacteristic());
                            }
                        }, 2000);

                        Log.d(TAG, "onReceive: BOND BONDED");

                        break;
                    case BOND_NONE:
                        // Oh oh
                        Log.d(TAG, "onReceive: BOND NONE");
                        break;
                }
            }
        }
    };

}

**Comment by weliem** [comment]
The reason I made the Blessed library is that you don't have to go through what your are going through now....I suggest you try the library.

But to give you an idea what is wrong with your code:
- Always close a GATT object after a disconnect and don't re-use the GATT object.
- You are not queuing your GATT operations and depending on the exact timing your operations will get 'stuck'
- You are not waiting for the result of writing the CCC descriptor and assume everything is ok
- You are using variables in your Runnables that have not been declared final. That will lead to unexpected results.
- Create one Handler object for all your operations and use it everywhere. That will guarantee operations are in the order your intend them to be executed
