### ISSUE TITLE
Use the library

### ISSUE THREAD

**Issue by helderalvesoliveira** [weliem/blessed-android#94]
Sorry I’m newer .
How I can add you library in my project ?

**Comment by mpashka** [comment]
Here is the answer https://jitpack.io/#weliem/blessed-android

**Comment by talatkuyuk** [comment]
That was my question, thanks to @mpashka for reply. I am building a BLE android application, and have realized that the things are getting complicated for handling queue and ble edge-cases, then, have decided to use this package, with Kotlin, one activity-multiple fragments structure, and using bound service, if I can manage this.

**Comment by weliem** [comment]
I added more explanation in the README.

As for using the library in Kotlin. There is nothing special to do. Just import it and use it...
