### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by MDXDave** [weliem/blessed-android#95]
Can you please add the possibility to disable the logging for the library *without* disable the general Timber Logging for the whole app? Would be nice 😄

**Comment by weliem** [comment]
Hi, that is not a bad idea. I will look into it.

So do I understand it correctly that you are using Timber in you application but you want to turn off the logging done by Blessed?

Or are you using a different logger?

**Comment by MDXDave** [comment]
Exactly, I use Timber within my app and want to disable the logging from Blessed, without disable the logging of my app itself. 😄

**Comment by weliem** [comment]
I added a function central.disableLogging()

**Comment by MDXDave** [comment]
Thanks for your quick response and implementation! It works as expected. Thank you!

**Comment by agap** [comment]
Is it possible to expose the logger to the outside world? I want to be able to turn it off, but I don't use `BluetoothCentralManager` as I only need `BluetoothPeripheral`. :) So creating `BluetoothCentralManager` only to be able to turn logging off seems like an overkill 🤔 

I can add a PR ofc, but I just wanted to know your opinion on that.

And thanks for the great library - it saved me a lot of headache!
